#!/bin/bash
#
# Installation script for xcodemcpwrapper
#
# This script installs the xcodemcpwrapper to ~/bin/
# making it available for use with Cursor, Claude Code, and Codex CLI.
#

set -e

INSTALL_WEBUI=false

for arg in "$@"; do
    case "$arg" in
        --webui)
            INSTALL_WEBUI=true
            ;;
        -h|--help)
            cat << 'EOF'
Usage: ./scripts/install.sh [--webui]

Options:
  --webui    Install optional Web UI dependencies (fastapi/uvicorn/etc)
  -h, --help Show this help message
EOF
            exit 0
            ;;
        *)
            echo -e "${RED}Error: Unknown option '$arg'${NC}"
            echo "Run ./scripts/install.sh --help for usage."
            exit 1
            ;;
    esac
done

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "xcodemcpwrapper Installer"
echo "==========================="
echo ""

# Check Python version
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2 | cut -d'.' -f1,2)
REQUIRED_VERSION="3.7"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo -e "${RED}Error: Python 3.7+ is required (found $PYTHON_VERSION)${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Python version check passed ($PYTHON_VERSION)${NC}"

# Create ~/bin if it doesn't exist
INSTALL_DIR="$HOME/bin"
if [ ! -d "$INSTALL_DIR" ]; then
    echo "Creating $INSTALL_DIR..."
    mkdir -p "$INSTALL_DIR"
fi

# Check if ~/bin is in PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo -e "${YELLOW}Warning: $INSTALL_DIR is not in your PATH${NC}"
    echo "Add the following to your ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"\$HOME/bin:\$PATH\""
    echo ""
fi

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Set up virtual environment if not already active
VENV_DIR="$PROJECT_ROOT/.venv"
if [ -z "$VIRTUAL_ENV" ]; then
    if [ ! -d "$VENV_DIR" ]; then
        echo "Creating virtual environment at $VENV_DIR..."
        python3 -m venv "$VENV_DIR"
    fi
    echo "Activating virtual environment..."
    source "$VENV_DIR/bin/activate"
fi

PYTHON_BIN="$(which python3)"

# Install using pip (inside venv)
if [ "$INSTALL_WEBUI" = true ]; then
    echo "Installing xcodemcpwrapper with Web UI dependencies..."
else
    echo "Installing xcodemcpwrapper..."
fi
cd "$PROJECT_ROOT"
if [ "$INSTALL_WEBUI" = true ]; then
    python3 -m pip install -e ".[webui]" --quiet
else
    python3 -m pip install -e . --quiet
fi

# Stop any running broker daemon so the new version takes over on next launch
BROKER_PID_FILE="$HOME/.mcpbridge_wrapper/broker.pid"
if [ -f "$BROKER_PID_FILE" ]; then
    BROKER_PID=$(cat "$BROKER_PID_FILE" 2>/dev/null)
    if [ -n "$BROKER_PID" ] && kill -0 "$BROKER_PID" 2>/dev/null; then
        echo "Stopping running broker daemon (PID $BROKER_PID)..."
        kill "$BROKER_PID" 2>/dev/null || true
        sleep 1
        if kill -0 "$BROKER_PID" 2>/dev/null; then
            sleep 2
        fi
    fi
    rm -f "$BROKER_PID_FILE" "$HOME/.mcpbridge_wrapper/broker.sock" "$HOME/.mcpbridge_wrapper/broker.version"
    echo -e "${GREEN}✓ Old broker daemon stopped${NC}"
fi

# Create wrapper script in ~/bin that uses the venv Python
cat > "$INSTALL_DIR/xcodemcpwrapper" << WRAPPER
#!/bin/bash
# xcodemcpwrapper launcher
# Generated by install.sh
# Uses the Python interpreter from the install-time environment

exec "$PYTHON_BIN" -m mcpbridge_wrapper "\$@"
WRAPPER

chmod +x "$INSTALL_DIR/xcodemcpwrapper"

echo -e "${GREEN}✓ Installed to $INSTALL_DIR/xcodemcpwrapper${NC}"

# Verify installation
if command -v xcodemcpwrapper &> /dev/null; then
    echo -e "${GREEN}✓ xcodemcpwrapper is available in PATH${NC}"
else
    echo -e "${YELLOW}⚠ xcodemcpwrapper may not be in PATH${NC}"
    echo "  You may need to restart your terminal or run:"
    echo "    export PATH=\"\$HOME/bin:\$PATH\""
fi

echo ""
echo "Installation complete!"
if [ "$INSTALL_WEBUI" = true ]; then
    echo -e "${GREEN}✓ Web UI dependencies installed (use --web-ui args in MCP client config)${NC}"
else
    echo -e "${YELLOW}Note: Installed without Web UI extras.${NC}"
    echo "      If you want to use --web-ui args, reinstall with:"
    echo "      ./scripts/install.sh --webui"
fi
echo ""
echo "Next steps:"
echo "  1. Ensure Xcode 26.3+ is installed"
echo "  2. Enable Xcode Tools MCP Server in Xcode > Settings > Intelligence"
echo "  3. Configure your MCP client (see config/ directory)"
echo ""
echo "Configuration examples:"
echo "  - Cursor:      config/cursor-mcp.json"
echo "  - Claude Code: config/claude-code.txt"
echo "  - Codex CLI:   config/codex-cli.txt"
