#!/bin/bash
#
# Installation script for xcodemcpwrapper
#
# This script installs the xcodemcpwrapper to ~/bin/
# making it available for use with Cursor, Claude Code, and Codex CLI.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "xcodemcpwrapper Installer"
echo "==========================="
echo ""

# Check Python version
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2 | cut -d'.' -f1,2)
REQUIRED_VERSION="3.7"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo -e "${RED}Error: Python 3.7+ is required (found $PYTHON_VERSION)${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Python version check passed ($PYTHON_VERSION)${NC}"

# Create ~/bin if it doesn't exist
INSTALL_DIR="$HOME/bin"
if [ ! -d "$INSTALL_DIR" ]; then
    echo "Creating $INSTALL_DIR..."
    mkdir -p "$INSTALL_DIR"
fi

# Check if ~/bin is in PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo -e "${YELLOW}Warning: $INSTALL_DIR is not in your PATH${NC}"
    echo "Add the following to your ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"\$HOME/bin:\$PATH\""
    echo ""
fi

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Install using pip
echo "Installing xcodemcpwrapper..."
cd "$PROJECT_ROOT"
pip3 install -e . --quiet

# Create wrapper script in ~/bin
cat > "$INSTALL_DIR/xcodemcpwrapper" << 'EOF'
#!/bin/bash
# xcodemcpwrapper launcher
# Generated by install.sh

exec python3 -m mcpbridge_wrapper "$@"
EOF

chmod +x "$INSTALL_DIR/xcodemcpwrapper"

echo -e "${GREEN}✓ Installed to $INSTALL_DIR/xcodemcpwrapper${NC}"

# Verify installation
if command -v xcodemcpwrapper &> /dev/null; then
    echo -e "${GREEN}✓ xcodemcpwrapper is available in PATH${NC}"
else
    echo -e "${YELLOW}⚠ xcodemcpwrapper may not be in PATH${NC}"
    echo "  You may need to restart your terminal or run:"
    echo "    export PATH=\"\$HOME/bin:\$PATH\""
fi

echo ""
echo "Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Ensure Xcode 26.3+ is installed"
echo "  2. Enable Xcode Tools MCP Server in Xcode > Settings > Intelligence"
echo "  3. Configure your MCP client (see config/ directory)"
echo ""
echo "Configuration examples:"
echo "  - Cursor:      config/cursor-mcp.json"
echo "  - Claude Code: config/claude-code.txt"
echo "  - Codex CLI:   config/codex-cli.txt"
